### ISSUE TITLE
GriffinND addback

### ISSUE THREAD

**Issue by SmithJK** [GRIFFINCollaboration/NTuple#15]
When creating the GriffinND histograms for angular correlations, it looks to me like the addback algorithm isn't actually adding anything back. It's calculating the crystal 1 and crystal 2 energies, but I don't see where these are added together, either when there's only one detector hit or when there are more than one detectors hit. @AndrewMac1, have you used the addback histograms for angular correlations?

**Comment by AndrewMac1** [comment]
When creating GriffinND there are three sparse histograms made. One uses fGriffinCrystal for the crystal energies, one uses fGriffinDetector which adds the energy in the AddbackGriffin function in Converter.cc and the other uses neighbour addback which isn't really used that often at this point, but feel free. Hope this helps.

**Comment by SmithJK** [comment]
`griffin_crystal_unsup_gamma_gamma_corr_edep_det_sparse` uses `GriffinDetMap`. Here's, it is adding together all the interactions that occur in a detector and setting their position to the center of the detector. This means there will be fewer than 52 opening angles (only 16x16 combinations instead of 64x64). This is consistent with what I see in the spectra, but not with the current addback algorithm used in the analysis code, which sets the position of the summed interaction to the center of the crystal with the highest energy (leaving us 64x60 combinations and all 52 opening angles).

By neighbor addback for `griffin_crystal_unsup_gamma_gamma_corr_edep_cry_addback_sparse`, do you mean an algorithm based on pure detector distance? Or an algorithm consistent with the analysis algorithm? In lines 950-998 of Converter.cc, there are calculations done that look like they are going to add together signals in the same detector when there are no other detectors present. This should produce an entry in the sum peak, but no histogram is ever filled. I _think_ this is eliminating the counts in opening angles one and three, but not adding them to opening angle zero, which is what is done in lines 944-949.

**Comment by AndrewMac1** [comment]
I see where you are looking now. This definitely looks like a mistake in the github version. I am away right now and don't have time to make a fix but I will be back in two days push a correction. It should be a rather easy fix I think when it says:

det1        = fGriffinDetector->at(firstDet).DetectorId();  (line 896)

It should say 

det1        = fGriffinDetector->at(firstDet).CrystalId();

instead. Also, The angle will have to be changed from GriffinDetMap to the GriffinCryMap and the few following lines for the index. If you wish to make them on your own please go ahead and do so. I will make the changes in a few days once I get back to the correct mappings. Good catch, thanks for spotting this!

----- Original Message -----

**Comment by AndrewMac1** [comment]
I was mixed up the names again and was looking at the wrong thing. Detector method does use the centre of the detectors unlike our analysis, don't worry about that version. Your are right there is a bug in the Github version and I think some lines got commented out accidentally when this was pushed. I haven't looked into it because I am jumping around from one hotel wifi to the next for the next two days but I think the fill lines (987,989 and 990) should not be commented out. Also, I think it should say:

Double_t fillval2abn[3] = {fGriffinDetector->at(0).Energy(), fGriffinDetector->at(0).Energy(),0.0};

for line 987. I may also need to be moved up to avoid double counting. I will look into the Github version when I get back and hopefully straighten this out in a few days but maybe try that and let me know.  

----- Original Message -----

**Comment by SmithJK** [comment]
This was fixed with merge #17 .
